#pragma once

#define ROBOT_SERVO_PIN 16

#define ROBOT_ULTRASONIC_TRIGGER_PIN 10
#define ROBOT_ULTRASONIC_ECHO_PIN 11
#define ROBOT_ULTRASONIC_TIMEOUT_US 25000

#define ROBOT_LEFT_MOTOR_IN1_PIN 2
#define ROBOT_LEFT_MOTOR_IN2_PIN 3
#define ROBOT_LEFT_MOTOR_PWM_PIN 4

#define ROBOT_RIGHT_MOTOR_IN1_PIN 6
#define ROBOT_RIGHT_MOTOR_IN2_PIN 7
#define ROBOT_RIGHT_MOTOR_PWM_PIN 8

#define ROBOT_LEFT_MOTOR_INVERTED 0
#define ROBOT_RIGHT_MOTOR_INVERTED 1

#define ROBOT_MOTOR_PWM_FREQUENCY_HZ 10000
#define ROBOT_MOTOR_PWM_WRAP 999

#define ROBOT_CRUISE_SPEED 0.70f
#define ROBOT_TURN_SPEED 0.65f

#define ROBOT_OBSTACLE_THRESHOLD_CM 20.0f

#define ROBOT_SERVO_CENTER_ANGLE 90
#define ROBOT_SCAN_MIN_ANGLE 20
#define ROBOT_SCAN_MAX_ANGLE 160
#define ROBOT_SCAN_STEP_ANGLE 10
#define ROBOT_SCAN_SERVO_SETTLE_MS 80

#define ROBOT_DISTANCE_PERIOD_MS 60
#define ROBOT_DISTANCE_WAIT_MS 200
#define ROBOT_TURN_DURATION_MS 500
#define ROBOT_POST_TURN_SETTLE_MS 150

#define ROBOT_TASK_STACK_SIZE 512

#define ROBOT_SENSOR_TASK_PRIORITY 3
#define ROBOT_MOVE_TASK_PRIORITY 2
#define ROBOT_SCAN_TASK_PRIORITY 2
#define ROBOT_DECISION_TASK_PRIORITY 2
